### ISSUE TITLE
Server crash sendHeldItem

### ISSUE THREAD

**Issue by jjplaying** [iTXTech/SynapseTransfer#3]
Hi, when I'm transferring a player from one server to another, the origin server is crashing:

```
[11:50:05] [Server thread/INFO]: thejjplaying[/10.0.0.4:19132] [ClientID: -1806032696] logged in with entity id 1 at (world, 90.9974, 24, 2.7795)
[11:50:11] [Server thread/INFO]: thejjplaying[/10.0.0.4:19132] logged out due to Transferred to 127.0.0.1:51935
[11:50:11] [Server thread/CRITICAL]: Error: "Call to a member function sendHeldItem() on null" (EXCEPTION) in "/src/pocketmine/Player" at line 2578
[11:50:11] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[11:50:11] [Server thread/EMERGENCY]: Please upload the "/Users/Jarne/Downloads/servers/lobby/crashdumps/CrashDump_Sat_Jul_2-11.50.11-CEST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[11:50:11] [Server thread/INFO]: Disabling BanSystem v1.0.0
[11:50:11] [Server thread/INFO]: Disabling ChatFilter v1.0.0
[11:50:11] [Server thread/INFO]: Disabling Core v1.0.0
[11:50:11] [Server thread/INFO]: Disabling Economy v1.0.0
[11:50:11] [Server thread/INFO]: Disabling FloatingText v1.0.0
[11:50:11] [Server thread/INFO]: Disabling Friends v1.0.0
[11:50:11] [Server thread/INFO]: Disabling Pets v1.0.0
[11:50:11] [Server thread/INFO]: Disabling PurePerms v1.3.7
[11:50:11] [Server thread/INFO]: Disabling VIP v1.0.0
[11:50:11] [Server thread/INFO]: Disabling VoteRank v1.0.0
[11:50:11] [Server thread/INFO]: Disabling Localization v1.0.0
[11:50:11] [Server thread/INFO]: Disabling Network v1.0.0
[11:50:11] [Server thread/INFO]: Disabling PureChat v1.3.3
[11:50:11] [Server thread/INFO]: Unloading level "world"
Killed: 9
Jarnes-iMac:lobby Jarne$ 
```

**Comment by ishitatsuyuki** [comment]
Attach your crashdump.

**Comment by jjplaying** [comment]
[CrashDump_Sat_Jul_2-11.54.21-CEST_2016.txt](https://github.com/iTXTech/SynapseTransfer/files/344487/CrashDump_Sat_Jul_2-11.54.21-CEST_2016.txt)

**Comment by Driesboy** [comment]
its the same isuess als login!
see here https://github.com/iTXTech/Genisys/issues/1331

**Comment by ishitatsuyuki** [comment]
If you have NPCs, it's the plugin's fault.

**Comment by Driesboy** [comment]
no its not 
this is the issues

if player have item in inv en quit en join back the server will crash

**Comment by Driesboy** [comment]
its the same with my server that have no npcs

**Comment by jjplaying** [comment]
I'm not using NCPs, only a self developed plugin which has the same structure like SynapseTransfer.
Anything wrong there?
When I run /network <server name>, sometimes everything works, sometimes, the origin server crashes but I'm transferred, and sometimes, origin server crashes and I'm kicked.

```
<?php
/**
 * Created by PhpStorm.
 * User: Jarne
 * Date: 02.07.16
 * Time: 11:27
 */

namespace jjplaying\Network;

use pocketmine\command\Command;
use pocketmine\command\CommandSender;
use pocketmine\plugin\PluginBase;
use synapse\Player;

class Network extends PluginBase {
    public function onEnable() {
        $this->saveDefaultConfig();
        $this->getServer()->getPluginManager()->registerEvents(new EventListener($this), $this);
    }

    public function onCommand(CommandSender $sender, Command $command, $label, array $args) {
        if($sender instanceof Player) {
            switch(strtolower($command->getName())) {
                case "network":
                    if(isset($args[0])) {
                        if($hash = $this->getClientHashByDescription($args[0])) {
                            $sender->transfer($hash);
                        }
                    }
                    return true;
                case "lobby":
                    $sender->transfer($this->getClientHashByDescription("lobby"));
                    return true;
                case "spawn":
                    $sender->teleport($this->getServer()->getDefaultLevel()->getSafeSpawn());
                    return true;
            }
        }

        return false;
    }

    /**
     * @param $description
     * @return array|false
     */
    public function getClientDataByDescription(string $description) {
        foreach($this->getServer()->getSynapse()->getClientData() as $data){
            if($data["description"] == $description) {
                return $data;
            }
        }

        return false;
    }

    /**
     * @param string $description
     * @return string|false
     */
    public function getClientHashByDescription(string $description) {
        foreach($this->getServer()->getSynapse()->getClientData() as $hash => $data) {
            if($data["description"] == $description) {
                return $hash;
            }
        }

        return false;
    }
}
```

**Comment by PeratX** [comment]
Check the latest Genisys version, this has been fixed.

**Comment by Driesboy** [comment]
dont work
same error

**Comment by jjplaying** [comment]
The bug is still there, but I've found out how to reproduce correctly. When you get transferred **by interacting** with something, e.g. tapping on a sign with PlayerInteractEvent, the origin server crashes.

**Comment by PeratX** [comment]
Then use a schedule transfer after the packet is fully proceed

**Comment by Driesboy** [comment]
but i have this on join after the 2e x
